---
- name: Desactivar swap
  ansible.builtin.shell: |
    swapoff -a
    sed -i '/\bswap\b/ s/^/#/' /etc/fstab

- name: Habilitar módulos del kernel
  ansible.builtin.shell: |
    modprobe overlay
    modprobe br_netfilter

- name: Configurar parámetros sysctl
  ansible.builtin.shell: |
    tee /etc/sysctl.d/kubernetes.conf<<EOF
    net.bridge.bridge-nf-call-ip6tables = 1
    net.bridge.bridge-nf-call-iptables = 1
    net.ipv4.ip_forward = 1
    EOF

- name: Recargar sysctl
  ansible.builtin.shell: |
    sysctl --system