- name: Crear configuración de módulos para containerd
  ansible.builtin.shell: |
    tee /etc/modules-load.d/containerd.conf <<EOF
    overlay
    br_netfilter
    EOF

- name: Instalar dependencias
  ansible.builtin.apt: 
    name:
      - gnupg2
      - software-properties-common
      - curl
      - ca-certificates
    state: present
    update_cache: yes

- name: Añadir el repositorio
  block:
    - name: Descargar clave GPG de Docker
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /tmp/docker.gpg
        mode: '0644'

    - name: Instalar clave GPG
      ansible.builtin.apt_key:
        file: /tmp/docker.gpg
        state: present

    - name: Agregar repositorio de Docker
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        update_cache: yes

    - name: Eliminar archivo temporal de clave GPG
      ansible.builtin.file:
        path: /tmp/docker.gpg
        state: absent

- name: Instalar containerd.io
  ansible.builtin.apt: 
    name:
      - containerd.io
    state: present

- name: Configurar containerd
  ansible.builtin.shell: |
    mkdir -p /etc/containerd
    containerd config default | sudo tee /etc/containerd/config.toml
    sed -i 's/SystemdCgroup \= false/SystemdCgroup \= true/g' /etc/containerd/config.toml
    systemctl restart containerd
    systemctl enable containerd